/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSUExTWNOeU1pNmlIQzEwTERKS3QranA5V3R2YVRFRWdzYWhSZFVQNFEyUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidUNhTmh2VnVGNTNZN1E3amY5Rk1QMnFGNlUrRmN3dUFRb1NVUWRSYUlEVT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpQ3h6RE5nQ3kwMGFiNHNKTXRjM1BYSGlaZDhqbU11dnJacU5KOTI5cUZFPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJaWjdrdWQrdW5TNFFBTlVnZ0xwUUJBa1Y5ek9OR0drWi9qVVpMQTNWb1JVPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjRNMlZNMUpIVm9iM1pFdllYM29pemlXOSt6cHFEa25mOG1kNDJTN3lDVnM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im5obkNaY01YMTFySEY1Skh6K1VzemZ2M2JuVzVoWHdPWE5kc2ZCai9PV3c9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS0xRUUowakJhTTkzeEhBSXh0YU1wSFZqaDE5LzJtRG5PNWhIUTNJS3BGcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaUdVQmg1NGtOWTFlVjJvbTlZMExFa0pSWERKV2RsRUYvR1BLb0puQnRCUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjVhemFoVS83dk81bkVLbTl0eWsxYTlUQ0JTUFpDeTFEeU5OakUwYnpNLzJqQ1NMNTlkTmdOMDRpbDZqSzhEZXdNUGJUR3lvV0g0bEhTR09rMHVTaGhnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6ODMsImFkdlNlY3JldEtleSI6InBQbWdpN2hNUkxOV2lBQXhBeERXclNuL0RPRkhxT2tTRFlPbU95L1JBTjA9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IkJzRDhZM2hHVHdXd25TMWFQb21nMFEiLCJwaG9uZUlkIjoiOGY2YzNiNzgtNTAzOS00MzM0LWExNTctZTZlMzZmYmUwMjFjIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InA2VnVQdTZxZlFMVEVQUVM0Zy9VWmllSUNWcz0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI5dHZXTlluVE9xalhjVGhXbHdhSXRSOXZLTE09In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiUFpQNFQ0RUUiLCJtZSI6eyJpZCI6IjIzNDkwMzE3NjcwNDg6MTZAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ1B1em1xZ0VFT2ZGc2JVR0dBUWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IjJ3Q0hmZzhjWktYKzNiU01DOUl4MGR3SGNOV3g4V1g3b293L2lrUVBOaGs9IiwiYWNjb3VudFNpZ25hdHVyZSI6Im1UTlA3UFZwb3RnZ3ZHR2JyN2RqMTlxL2ZWNDJRaXQ4Y2hIbGJldzJsWnZmRzRzYUxpZzlpcEE1MWJnWDhybDhUcHNvUEVyeXhaNmdOYjhhcDJhTENRPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJJV3hhTlEyblVVTFI0QWZ2V1FvRTRoa3ZlSVpmSko5RWJ4K1RpUHhMVVRNVlcwcFYrQmxWcGZKWnpERENDR0ZTRy9MaGl4aFpPWktpQmJtTTNZSitoQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIzNDkwMzE3NjcwNDg6MTZAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCZHNBaDM0UEhHU2wvdDIwakF2U01kSGNCM0RWc2ZGbCs2S01QNHBFRHpZWiJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTcyMjU3MzU1Nn0=';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "234";
const author = process.env.STICKER_AUTHOR || 'fortunatus';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '2349031767048';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'OGAAH🇳🇬'🗿;
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'true';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || '';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'false';
const autobio = process.env.AUTOBIO || 'true';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session
};
